### ISSUE TITLE
Prevent player from holding down space to pass ice stage

### ISSUE THREAD

**Issue by ThePlasmak** [cydtseng/Tardigrade#18]

**Comment by pyuxiang** [comment]
Propose we abandon this:

- Holding down space is a different mechanic from the space scene, which makes it a bit more unique
- Initial heat has already been set to around 20% instead, so it's a quick time event of sorts
- Changing it from a button spam to a button hold doesn't detract from the narrative
- The more chill method of passing the stage is kind of in line with the music, i.e. chill and calm

**Comment by ThePlasmak** [comment]
Hm I agree that changing the mechanic works for variety—though if we're holding down space:
- The scene should a little after the bar is full?
- The tardigrade should have a shiver animation (which we can't really do well, even with shivering in-engine, unless we ask the art team to animate more)

**Comment by pyuxiang** [comment]
Yeah, we can probably implement the shivering ourselves by doing a rapid oscillations along the horizontal, but probably not going to be as aesthetic.

The bar full option can be done, lemme work on that.

**Comment by pyuxiang** [comment]
Done
