### ISSUE TITLE
Space scene: start compression amount somewhere in the middle, so the player has to spam space more

### ISSUE THREAD

**Issue by ThePlasmak** [cydtseng/Tardigrade#19]

**Comment by pyuxiang** [comment]
Starting from the middle results in an immediate squeezed state, and destroys the illusion of continuity. Implemented something similar to this effect, but by forcing a lower initial "compression resistance" value until a progress bar threshold (currently about 30%) is reached, before resetting the value. Kinda like an almost-forced loss trope.
